import type { Permission } from '@/server/auth/permissions'
import type { LauncherIcon } from './launcher-apps'

/**
 * Front doors for every module besides Sales, which keeps its own list.
 * Same tile shape as Sales: a coloured mark, a label, a one-line purpose.
 */
export type HubApp = {
  key: string
  label: string
  href: string
  icon: LauncherIcon
  permission?: Permission
  accent: string
  wash: string
  blurb: string
}

export const PURCHASE_HUB_APPS: HubApp[] = [
  {
    key: 'bills',
    label: 'Bills',
    href: '/purchases/bills/new',
    icon: 'receipt',
    permission: 'bill:create',
    accent: '#C2410C',
    wash: '#FFEDD5',
    blurb: 'You owe the vendor',
  },
  {
    key: 'expenses',
    label: 'Expenses',
    href: '/purchases/expenses/new',
    icon: 'banknote',
    permission: 'expense:create',
    accent: '#B45309',
    wash: '#FEF3C7',
    blurb: 'Paid on the spot',
  },
  {
    key: 'vendor-credits',
    label: 'Vendor credits',
    href: '/purchases/vendor-credits/new',
    icon: 'hand-coins',
    permission: 'bill:create',
    accent: '#BE123C',
    wash: '#FFE4E6',
    blurb: 'Reduce what you owe',
  },
  {
    key: 'purchase-orders',
    label: 'Purchase orders',
    href: '/purchases/purchase-orders/new',
    icon: 'clipboard',
    permission: 'bill:create',
    accent: '#0369A1',
    wash: '#E0F2FE',
    blurb: 'Not received yet',
  },
  {
    key: 'delivery',
    label: 'Delivery',
    href: '/purchases/delivery',
    icon: 'package',
    permission: 'bill:read',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'Arrived or still due',
  },
  {
    key: 'bill-payments',
    label: 'Bill payments',
    href: '/bill-payments/new',
    icon: 'wallet',
    permission: 'expense:create',
    accent: '#0E7490',
    wash: '#CFFAFE',
    blurb: 'Money paid out',
  },
  {
    key: 'vendors',
    label: 'Vendors',
    href: '/vendors',
    icon: 'building',
    permission: 'vendor:read',
    accent: '#7C2D12',
    wash: '#FFEDD5',
    blurb: 'Who you buy from',
  },
  {
    key: 'reports',
    label: 'Reports',
    href: '/purchases/reports',
    icon: 'trending',
    permission: 'report:read',
    accent: '#334155',
    wash: '#F1F5F9',
    blurb: 'Where the money goes',
  },
]

/** Work inside the Delivery app under Purchases. */
export const DELIVERY_HUB_APPS: HubApp[] = [
  {
    key: 'receive',
    label: 'Receive items',
    href: '/purchases/purchase-orders?status=open',
    icon: 'package',
    permission: 'bill:create',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'Book a delivery in',
  },
  {
    key: 'outstanding',
    label: 'Outstanding',
    href: '/purchases/delivery/outstanding',
    icon: 'clock',
    permission: 'bill:read',
    accent: '#B45309',
    wash: '#FEF3C7',
    blurb: 'Not yet received',
  },
  {
    key: 'delivered',
    label: 'Delivered',
    href: '/purchases/delivery/received',
    icon: 'clipboard',
    permission: 'bill:read',
    accent: '#047857',
    wash: '#D1FAE5',
    blurb: 'Orders complete',
  },
  {
    key: 'delivery-report',
    label: 'Delivery report',
    href: '/purchases/delivery/report',
    icon: 'trending',
    permission: 'bill:read',
    accent: '#0369A1',
    wash: '#E0F2FE',
    blurb: 'Line by line',
  },
  {
    key: 'purchase-orders',
    label: 'Purchase orders',
    href: '/purchases/purchase-orders',
    icon: 'file',
    permission: 'bill:read',
    accent: '#334155',
    wash: '#F1F5F9',
    blurb: 'Every order',
  },
]

export const PURCHASE_REPORT_APPS: HubApp[] = [
  {
    key: 'delivery-report',
    label: 'Purchase delivery',
    href: '/purchases/delivery/report',
    icon: 'package',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'Received vs outstanding',
  },
  {
    key: 'purchases-by-vendor',
    label: 'Purchases by Vendor Summary',
    href: '/reports/purchases-by-vendor',
    icon: 'building',
    accent: '#C2410C',
    wash: '#FFEDD5',
    blurb: 'Where the buying goes',
  },
  {
    key: 'purchases-by-item',
    label: 'Purchases by Product/Service',
    href: '/reports/purchases-by-item',
    icon: 'package',
    accent: '#1D4ED8',
    wash: '#DBEAFE',
    blurb: 'What was bought',
  },
  {
    key: 'expenses-by-category',
    label: 'Expenses by Account',
    href: '/reports/expenses-by-category',
    icon: 'banknote',
    accent: '#B45309',
    wash: '#FEF3C7',
    blurb: 'Spending by account',
  },
  {
    key: 'expenses-by-vendor',
    label: 'Expenses by Vendor Summary',
    href: '/reports/expenses-by-vendor',
    icon: 'receipt',
    accent: '#7C2D12',
    wash: '#FFEDD5',
    blurb: 'Net of tax',
  },
  {
    key: 'ap-aging',
    label: 'A/P Aging Summary',
    href: '/reports/ap-aging',
    icon: 'calendar',
    accent: '#BE123C',
    wash: '#FFE4E6',
    blurb: 'What is overdue',
  },
  {
    key: 'unpaid-bills',
    label: 'Unpaid bills',
    href: '/reports/unpaid-bills',
    icon: 'clipboard',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'The pay-day list',
  },
  {
    key: 'payments-made',
    label: 'Bill Payment List',
    href: '/reports/payments-made',
    icon: 'hand-coins',
    accent: '#047857',
    wash: '#D1FAE5',
    blurb: 'Cash paid',
  },
  {
    key: 'vendor-balances',
    label: 'Vendor Balance Summary',
    href: '/reports/vendor-balances',
    icon: 'wallet',
    accent: '#0369A1',
    wash: '#E0F2FE',
    blurb: 'Owed per vendor',
  },
  {
    key: 'vendor-statements',
    label: 'Vendor Balance Detail',
    href: '/reports/statements/vendor',
    icon: 'book',
    accent: '#334155',
    wash: '#F1F5F9',
    blurb: 'One vendor, one period',
  },
]

export const BANKING_HUB_APPS: HubApp[] = [
  {
    key: 'accounts',
    label: 'Accounts',
    href: '/banking/accounts',
    icon: 'wallet',
    permission: 'bank:read',
    accent: '#047857',
    wash: '#D1FAE5',
    blurb: 'What the bank holds',
  },
  {
    key: 'transfer',
    label: 'Transfer',
    href: '/banking/transfers/new',
    icon: 'transfer',
    permission: 'bank:transact',
    accent: '#0369A1',
    wash: '#E0F2FE',
    blurb: 'Move money',
  },
  {
    key: 'deposit',
    label: 'Deposit',
    href: '/banking/deposits/new',
    icon: 'banknote',
    permission: 'bank:transact',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'Into the bank',
  },
  {
    key: 'import',
    label: 'Import',
    href: '/banking/import',
    icon: 'file',
    permission: 'bank:import',
    accent: '#1D4ED8',
    wash: '#DBEAFE',
    blurb: 'A statement',
  },
]

export const INVENTORY_HUB_APPS: HubApp[] = [
  {
    key: 'items',
    label: 'Products',
    href: '/items',
    icon: 'package',
    permission: 'item:read',
    accent: '#1D4ED8',
    wash: '#DBEAFE',
    blurb: 'What you sell and buy',
  },
  {
    key: 'categories',
    label: 'Categories',
    href: '/items/categories',
    icon: 'package',
    permission: 'item:read',
    accent: '#714B67',
    wash: '#F3EEF2',
    blurb: 'Building, plumbing, electrical…',
  },
  {
    key: 'stock',
    label: 'Stock on hand',
    href: '/inventory/stock',
    icon: 'clipboard',
    permission: 'inventory:read',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'Quantity and value',
  },
  {
    key: 'stores',
    label: 'Store',
    href: '/stores',
    icon: 'building',
    permission: 'inventory:read',
    accent: '#1E3A5F',
    wash: '#E2E8F0',
    blurb: 'Office home · all stores',
  },
  {
    key: 'adjust',
    label: 'Adjust stock',
    href: '/inventory/adjustments/new',
    icon: 'sliders',
    permission: 'inventory:adjust',
    accent: '#B45309',
    wash: '#FEF3C7',
    blurb: 'A count that differs',
  },
  {
    key: 'reports',
    label: 'Reports',
    href: '/inventory/reports',
    icon: 'trending',
    permission: 'report:read',
    accent: '#7C2D12',
    wash: '#FFEDD5',
    blurb: 'What moved',
  },
]

export const INVENTORY_REPORT_APPS: HubApp[] = [
  {
    key: 'inventory-valuation',
    label: 'Inventory Valuation Summary',
    href: '/reports/inventory-valuation',
    icon: 'package',
    accent: '#1D4ED8',
    wash: '#DBEAFE',
    blurb: 'What it is worth',
  },
  {
    key: 'inventory-movements',
    label: 'Inventory Movement',
    href: '/reports/inventory-movements',
    icon: 'clipboard',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'What came and went',
  },
  {
    key: 'inventory-reorder',
    label: 'Products to Reorder',
    href: '/reports/inventory-reorder',
    icon: 'clock',
    accent: '#BE123C',
    wash: '#FFE4E6',
    blurb: 'Below the point',
  },
  {
    key: 'inventory-cost-change',
    label: 'Cost up or down',
    href: '/reports/inventory-cost-change',
    icon: 'trending',
    accent: '#C2410C',
    wash: '#FFEDD5',
    blurb: 'Higher or lower cost',
  },
]

export const ACCOUNTING_HUB_APPS: HubApp[] = [
  {
    key: 'accounts',
    label: 'Chart of accounts',
    href: '/accounts',
    icon: 'book',
    permission: 'account:read',
    accent: '#1E3A5F',
    wash: '#E2E8F0',
    blurb: 'Every account',
  },
  {
    key: 'journals',
    label: 'Journal entries',
    href: '/journals',
    icon: 'notebook',
    permission: 'journal:read',
    accent: '#334155',
    wash: '#F1F5F9',
    blurb: 'What was posted',
  },
  {
    key: 'new-journal',
    label: 'New entry',
    href: '/journals/new',
    icon: 'scroll',
    permission: 'journal:create',
    accent: '#0369A1',
    wash: '#E0F2FE',
    blurb: 'Write one by hand',
  },
  {
    key: 'periods',
    label: 'Periods',
    href: '/periods',
    icon: 'calendar',
    permission: 'period:read',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'Close the month',
  },
  {
    key: 'reports',
    label: 'Reports',
    href: '/accounting/reports',
    icon: 'trending',
    permission: 'report:read',
    accent: '#7C2D12',
    wash: '#FFEDD5',
    blurb: 'The workings',
  },
]

export const ACCOUNTING_REPORT_APPS: HubApp[] = [
  {
    key: 'general-ledger',
    label: 'General Ledger',
    href: '/reports/general-ledger',
    icon: 'book',
    accent: '#1E3A5F',
    wash: '#E2E8F0',
    blurb: 'Every posted line',
  },
  {
    key: 'journal-report',
    label: 'Journal',
    href: '/reports/journal-report',
    icon: 'scroll',
    accent: '#334155',
    wash: '#F1F5F9',
    blurb: 'Both sides',
  },
  {
    key: 'account-balances',
    label: 'Account List',
    href: '/reports/account-balances',
    icon: 'scale',
    accent: '#0369A1',
    wash: '#E0F2FE',
    blurb: 'Open, move, close',
  },
  {
    key: 'account-statement',
    label: 'Account QuickReport',
    href: '/reports/statements/account',
    icon: 'file',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'One account',
  },
  {
    key: 'trial-balance',
    label: 'Trial balance',
    href: '/reports/trial-balance',
    icon: 'scale',
    accent: '#1D4ED8',
    wash: '#DBEAFE',
    blurb: 'Debits equal credits',
  },
  {
    key: 'adjusting-entries',
    label: 'Adjusting Journal Entries',
    href: '/reports/adjusting-entries',
    icon: 'sliders',
    accent: '#B45309',
    wash: '#FEF3C7',
    blurb: 'Year-end entries',
  },
]

export const SETTINGS_HUB_APPS: HubApp[] = [
  {
    key: 'organization',
    label: 'Organisation',
    href: '/settings/organization',
    icon: 'building',
    accent: '#0B4F6C',
    wash: '#E0F2FE',
    blurb: 'Name and year',
  },
  {
    key: 'features',
    label: 'Configuration',
    href: '/settings/features',
    icon: 'sliders',
    permission: 'org:update',
    accent: '#714B67',
    wash: '#F3EAF1',
    blurb: 'Turn apps and deletes on or off',
  },
  {
    key: 'accounts',
    label: 'Default accounts',
    href: '/settings/accounts',
    icon: 'book',
    permission: 'account:read',
    accent: '#1E3A5F',
    wash: '#E2E8F0',
    blurb: 'Where postings land',
  },
  {
    key: 'payment-terms',
    label: 'Payment terms',
    href: '/settings/payment-terms',
    icon: 'calendar',
    accent: '#0369A1',
    wash: '#E0F2FE',
    blurb: 'When money is due',
  },
  {
    key: 'tax',
    label: 'Tax',
    href: '/settings/tax',
    icon: 'percent',
    permission: 'tax:read',
    accent: '#BE123C',
    wash: '#FFE4E6',
    blurb: 'Rates and codes',
  },
  {
    key: 'users',
    label: 'Users',
    href: '/settings/users',
    icon: 'users',
    permission: 'user:read',
    accent: '#1D4ED8',
    wash: '#DBEAFE',
    blurb: 'Roles, apps & who can sign in',
  },
  {
    key: 'templates',
    label: 'Templates',
    href: '/settings/templates',
    icon: 'file',
    permission: 'org:read',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'Invoice paper for the whole system',
  },
  {
    key: 'appearance',
    label: 'Appearance',
    href: '/settings/appearance',
    icon: 'palette',
    accent: '#6D28D9',
    wash: '#EDE9FE',
    blurb: 'Colour of the books',
  },
  {
    key: 'profile',
    label: 'Your profile',
    href: '/settings/profile',
    icon: 'settings',
    accent: '#57534E',
    wash: '#F5F5F4',
    blurb: 'Name and password',
  },
  {
    key: 'backup',
    label: 'Backup',
    href: '/settings/backup',
    icon: 'file',
    permission: 'org:update',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'A copy of the books',
  },
  {
    key: 'activity',
    label: 'Activity',
    href: '/settings/activity',
    icon: 'scroll',
    permission: 'audit:read',
    accent: '#334155',
    wash: '#F1F5F9',
    blurb: 'What changed',
  },
]

export const HELP_HUB_APPS: HubApp[] = [
  {
    key: 'guide',
    label: 'Guide',
    href: '/help/guide',
    icon: 'book',
    accent: '#0F766E',
    wash: '#CCFBF1',
    blurb: 'The order of work',
  },
  {
    key: 'shortcuts',
    label: 'Shortcuts',
    href: '/help/shortcuts',
    icon: 'sliders',
    accent: '#0369A1',
    wash: '#E0F2FE',
    blurb: 'Two keys',
  },
  {
    key: 'ledger',
    label: 'The ledger',
    href: '/help/ledger',
    icon: 'scale',
    accent: '#1E3A5F',
    wash: '#E2E8F0',
    blurb: 'Why it balances',
  },
]

export function visibleHubApps(
  apps: HubApp[],
  permissions: ReadonlySet<string> | Iterable<string>,
): HubApp[] {
  const allowed = permissions instanceof Set ? permissions : new Set(permissions)
  return apps.filter((app) => !app.permission || allowed.has(app.permission))
}
