import { withoutBusinessOverview } from '@/lib/business-overview-access'

import type { LauncherSection } from './app-launcher'

/**
 * The report catalogue, named and grouped the way QuickBooks Online groups its
 * standard reports. Each tile opens a report that reads the ledger or the
 * documents that posted to it.
 */
export const REPORT_SECTIONS: LauncherSection[] = [
  {
    label: 'Business overview',
    blurb: 'The statements an accountant reads first.',
    apps: [
      {
        key: 'business-overview',
        label: 'Business overview',
        href: '/reports/business-overview',
        icon: 'trending',
        accent: '#0F766E',
        wash: '#CCFBF1',
        blurb: 'Cash, profit, and what is unpaid',
      },
      {
        key: 'profit-loss',
        label: 'Profit and Loss',
        href: '/reports/profit-loss',
        icon: 'trending',
        accent: '#0F766E',
        wash: '#CCFBF1',
        blurb: 'Income and expenses',
      },
      {
        key: 'balance-sheet',
        label: 'Balance Sheet',
        href: '/reports/balance-sheet',
        icon: 'scale',
        accent: '#1D4ED8',
        wash: '#DBEAFE',
        blurb: 'Assets, liabilities, equity',
      },
      {
        key: 'cash-flow',
        label: 'Statement of Cash Flows',
        href: '/reports/cash-flow',
        icon: 'wallet',
        accent: '#0369A1',
        wash: '#E0F2FE',
        blurb: 'How profit became cash',
      },
      {
        key: 'trial-balance',
        label: 'Trial Balance',
        href: '/reports/trial-balance',
        icon: 'scale',
        accent: '#1E3A5F',
        wash: '#E2E8F0',
        blurb: 'Debits equal credits',
      },
    ],
  },
  {
    label: 'Who owes you',
    blurb: 'Customers, open invoices, and what is past due.',
    apps: [
      {
        key: 'ar-aging',
        label: 'A/R Aging Summary',
        href: '/reports/ar-aging',
        icon: 'calendar',
        accent: '#BE123C',
        wash: '#FFE4E6',
        blurb: 'How long invoices have been due',
      },
      {
        key: 'customer-balances',
        label: 'Customer Balance Summary',
        href: '/reports/customer-balances',
        icon: 'wallet',
        accent: '#B45309',
        wash: '#FEF3C7',
        blurb: 'What each customer owes',
      },
      {
        key: 'customer-balance-detail',
        label: 'Customer Balance Detail',
        href: '/reports/statements/customer',
        icon: 'book',
        accent: '#334155',
        wash: '#F1F5F9',
        blurb: 'One customer, every charge',
      },
      {
        key: 'open-invoices',
        label: 'Open Invoices',
        href: '/reports/open-invoices',
        icon: 'notebook',
        accent: '#0F766E',
        wash: '#CCFBF1',
        blurb: 'Still unpaid',
      },
      {
        key: 'invoice-list',
        label: 'Invoice List',
        href: '/reports/invoice-list',
        icon: 'file',
        accent: '#0369A1',
        wash: '#E0F2FE',
        blurb: 'Every invoice in the period',
      },
      {
        key: 'collections',
        label: 'Collections Report',
        href: '/reports/collections',
        icon: 'hand-coins',
        accent: '#BE123C',
        wash: '#FFE4E6',
        blurb: 'Past due, with a phone number',
      },
      {
        key: 'payments-received',
        label: 'Invoice Payment List',
        href: '/reports/payments-received',
        icon: 'receipt',
        accent: '#047857',
        wash: '#D1FAE5',
        blurb: 'Money received',
      },
    ],
  },
  {
    label: 'Sales and customers',
    blurb: 'Who bought, and what they bought.',
    apps: [
      {
        key: 'sales-by-customer',
        label: 'Sales by Customer Summary',
        href: '/reports/sales-by-customer',
        icon: 'users',
        accent: '#0369A1',
        wash: '#E0F2FE',
        blurb: 'Income by customer',
      },
      {
        key: 'sales-by-item',
        label: 'Sales by Product/Service Summary',
        href: '/reports/sales-by-item',
        icon: 'package',
        accent: '#1D4ED8',
        wash: '#DBEAFE',
        blurb: 'Income by item',
      },
      {
        key: 'product-profitability',
        label: 'Product Profitability',
        href: '/reports/product-profitability',
        icon: 'trending',
        accent: '#7C2D12',
        wash: '#FFEDD5',
        blurb: 'Income against cost',
      },
    ],
  },
  {
    label: 'What you owe',
    blurb: 'Vendors, open bills, and payments.',
    apps: [
      {
        key: 'ap-aging',
        label: 'A/P Aging Summary',
        href: '/reports/ap-aging',
        icon: 'calendar',
        accent: '#BE123C',
        wash: '#FFE4E6',
        blurb: 'How long bills have been due',
      },
      {
        key: 'vendor-balances',
        label: 'Vendor Balance Summary',
        href: '/reports/vendor-balances',
        icon: 'wallet',
        accent: '#B45309',
        wash: '#FEF3C7',
        blurb: 'What each vendor is owed',
      },
      {
        key: 'vendor-balance-detail',
        label: 'Vendor Balance Detail',
        href: '/reports/statements/vendor',
        icon: 'book',
        accent: '#334155',
        wash: '#F1F5F9',
        blurb: 'One vendor, every bill',
      },
      {
        key: 'unpaid-bills',
        label: 'Unpaid Bills',
        href: '/reports/unpaid-bills',
        icon: 'clipboard',
        accent: '#0F766E',
        wash: '#CCFBF1',
        blurb: 'Still to pay',
      },
      {
        key: 'bill-list',
        label: 'Bill List',
        href: '/reports/bill-list',
        icon: 'file',
        accent: '#0369A1',
        wash: '#E0F2FE',
        blurb: 'Every bill in the period',
      },
      {
        key: 'payments-made',
        label: 'Bill Payment List',
        href: '/reports/payments-made',
        icon: 'hand-coins',
        accent: '#047857',
        wash: '#D1FAE5',
        blurb: 'Money paid',
      },
    ],
  },
  {
    label: 'Expenses and vendors',
    blurb: 'Where the spending went.',
    apps: [
      {
        key: 'expenses-by-vendor',
        label: 'Expenses by Vendor Summary',
        href: '/reports/expenses-by-vendor',
        icon: 'receipt',
        accent: '#7C2D12',
        wash: '#FFEDD5',
        blurb: 'Spend by vendor',
      },
      {
        key: 'purchases-by-vendor',
        label: 'Purchases by Vendor Summary',
        href: '/reports/purchases-by-vendor',
        icon: 'building',
        accent: '#C2410C',
        wash: '#FFEDD5',
        blurb: 'Bills and expenses',
      },
      {
        key: 'purchases-by-item',
        label: 'Purchases by Product/Service',
        href: '/reports/purchases-by-item',
        icon: 'package',
        accent: '#1D4ED8',
        wash: '#DBEAFE',
        blurb: 'What was bought',
      },
      {
        key: 'expenses-by-category',
        label: 'Expenses by Account',
        href: '/reports/expenses-by-category',
        icon: 'banknote',
        accent: '#B45309',
        wash: '#FEF3C7',
        blurb: 'Spend by expense account',
      },
    ],
  },
  {
    label: 'Sales tax',
    blurb: 'Tax collected and tax paid.',
    apps: [
      {
        key: 'tax-summary',
        label: 'Sales Tax Liability',
        href: '/reports/tax-summary',
        icon: 'percent',
        accent: '#7C2D12',
        wash: '#FFEDD5',
        blurb: 'Collected, paid, and owed',
      },
    ],
  },
  {
    label: 'For my accountant',
    blurb: 'The workings behind the statements.',
    apps: [
      {
        key: 'account-balances',
        label: 'Account List',
        href: '/reports/account-balances',
        icon: 'book',
        accent: '#1E3A5F',
        wash: '#E2E8F0',
        blurb: 'The chart, with balances',
      },
      {
        key: 'general-ledger',
        label: 'General Ledger',
        href: '/reports/general-ledger',
        icon: 'scroll',
        accent: '#334155',
        wash: '#F1F5F9',
        blurb: 'Every posted line',
      },
      {
        key: 'journal-report',
        label: 'Journal',
        href: '/reports/journal-report',
        icon: 'notebook',
        accent: '#0F766E',
        wash: '#CCFBF1',
        blurb: 'Both sides of each entry',
      },
      {
        key: 'transaction-detail',
        label: 'Transaction Detail by Account',
        href: '/reports/transaction-detail',
        icon: 'file',
        accent: '#0369A1',
        wash: '#E0F2FE',
        blurb: 'One account, every line',
      },
      {
        key: 'account-statement',
        label: 'Account QuickReport',
        href: '/reports/statements/account',
        icon: 'clipboard',
        accent: '#1D4ED8',
        wash: '#DBEAFE',
        blurb: 'Running balance',
      },
      {
        key: 'adjusting-entries',
        label: 'Adjusting Journal Entries',
        href: '/reports/adjusting-entries',
        icon: 'sliders',
        accent: '#B45309',
        wash: '#FEF3C7',
        blurb: 'Period-end entries',
      },
    ],
  },
  {
    label: 'Inventory',
    blurb: 'What is on hand, what moved, and what to reorder.',
    apps: [
      {
        key: 'inventory-valuation',
        label: 'Inventory Valuation Summary',
        href: '/reports/inventory-valuation',
        icon: 'package',
        accent: '#1D4ED8',
        wash: '#DBEAFE',
        blurb: 'Quantity and value',
      },
      {
        key: 'inventory-movements',
        label: 'Inventory Movement',
        href: '/reports/inventory-movements',
        icon: 'clipboard',
        accent: '#0F766E',
        wash: '#CCFBF1',
        blurb: 'What came and went',
      },
      {
        key: 'inventory-reorder',
        label: 'Products to Reorder',
        href: '/reports/inventory-reorder',
        icon: 'clock',
        accent: '#BE123C',
        wash: '#FFE4E6',
        blurb: 'At or below the point',
      },
      {
        key: 'inventory-cost-change',
        label: 'Cost up or down',
        href: '/reports/inventory-cost-change',
        icon: 'trending',
        accent: '#C2410C',
        wash: '#FFEDD5',
        blurb: 'Higher or lower cost',
      },
    ],
  },
  {
    label: 'Data analysis',
    blurb: 'Who did the work, and where the cash sales were deposited.',
    apps: [
      {
        key: 'user-activity',
        label: 'User Activity',
        href: '/reports/user-activity',
        icon: 'scroll',
        accent: '#1E3A5F',
        wash: '#E2E8F0',
        blurb: 'Every action in the period',
      },
      {
        key: 'activity-by-user',
        label: 'Activity by User',
        href: '/reports/activity-by-user',
        icon: 'users',
        accent: '#0369A1',
        wash: '#E0F2FE',
        blurb: 'How much each person did',
      },
      {
        key: 'sales-by-deposit',
        label: 'Sales by Deposit Account',
        href: '/reports/sales-by-deposit',
        icon: 'wallet',
        accent: '#047857',
        wash: '#D1FAE5',
        blurb: 'Where cash sales landed',
      },
    ],
  },
]

/** Catalogue tiles the caller may open. The business overview tile is not a general report. */
export function reportSectionsFor(
  permissions: ReadonlySet<string> | Iterable<string>,
): LauncherSection[] {
  return REPORT_SECTIONS.map((section) => ({
    ...section,
    apps: withoutBusinessOverview(section.apps, permissions),
  })).filter((section) => section.apps.length > 0)
}
